### PR TITLE
Token dependent indention

### LINKED ISSUE #104: Decide on the  usage of the `newlines` attribute
A few rules still use `newlines`, which leads to problems since all line-break rules only modify `lag_newlines`, so `newlines` may contain outdated information. 
Also, if we want to allow non-invasive styling without indention correction, we need to set spaces only for tokens that are not at the end of a line. Otherwise, we "destroy" the indention information provided in the raw data. 
One may think we could use `dplyr::lead(pd$lag_newlines)`, which may work since to create `lag_newlines`, we only introduced one unknown value (at the top of the parse table) as this was done in the flat structure. Using `dplyr::lead(pd$lag_newlines)` in each nested structure will create one unknown value for the last token (instead of `pd$newlines(nrow(pd))`. We may loose information

We may need another visitor to update `newlines` (or update it right in the place where we update `lag_newlines`) so we can use this attribute when manipulating spacing information (i.e. making sure we do not update spacing information for the last token on a line).

### LINKED ISSUE #105: Allow styling without modifying indention
This seems possible by adapting #94.

### PR DESCRIPTION
**Pull request by lorenzwalthert**
This PR consists of two parts:

**Step 1: Allow for token-dependent indention**
This implements #94 (and hence #66) rudimentary. By flattening out the nested parse table completely and computing the absolute position a token will take when serialised, we can use a look-up approach to set the indention of any token dependent on the indention of another token. There is room for improvement since `set_token_dependent_indention()` is really just work in progress and can be improved.

**Step 2: Allow for styling without touching indention**
Since step 1 implies to merge the spacing and indention information in `enrich_terminals()`into the column `spaces`, we are also able to discard the indention computed and use what we called raw indention, that is, take the indention from the input and don't modify it. The only thing for it to work is to not overwrite the spacing information if there is a line break after a token, which is checked via `newlines`. Since we modify `lag_newlines` before (in R/rules-line_breaks.R) and not `newlines`, this attribute needs to be updated after line breaks are set (closes #104). Hence, step 2 closes #105 and lays the foundations for #85.

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
I think this is quite a bit to review. Maybe we should even split it up. I believe that the code is not too bad, apart from everything in R/indent-token-dependent. I think I still have not found a good way of indenting token-dependent. It's all based on indices and maybe there are simpler ways to solve it. 
Since for the tidyverse style guide, we only have token-dependent indention, we would not to have to bother about everything that is not a function declaration, but I found it better to solve the function calls also, i.e. 
```r
call(1, 
     3)
```
And then add a rule that turns that into
```r
call(
  1, 
  3)
```
Or even
```r
call(
  1, 
  3
)
```

**Comment by krlmlr** [comment]
If you can split it into smaller pieces, please do by all means -- these will be much easier to review.

**Comment by lorenzwalthert** [comment]
Ok, will do so. Will require some time though.

**Comment by lorenzwalthert** [comment]
This PR was split up in the above referenced pull requests and can hence be closed.

**Pull request closed without merging**
