### PR TITLE
Improve YAML formatting for pkgdown

### PR DESCRIPTION
**Pull request by IndrajeetPatil**
Also rename fileext: yml -> yaml

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
Did you use a formatter or format manually?

**Comment by IndrajeetPatil** [comment]
I used VS Code's YAML formatter

**Comment by IndrajeetPatil** [comment]
@lorenzwalthert Did you need any further clarifications on this PR?

**Comment by lorenzwalthert** [comment]
No. I was wondering if we should add a pre-commit hook for YAML formatting (and I remembered there weren’t any popularones at the time I checked last time) and I found the there is one by Google now and I might use it in the future (https://github.com/google/yamlfmt/issues/58).

**Review by lorenzwalthert — APPROVED** [review]

**Pull request merged**
