### PR TITLE
Reorganize code

### PR DESCRIPTION
**Pull request by krlmlr**
- extract compute_parse_data_flat_with_ws() and compute_parse_data_nested()
- new modules nested.R (for everything related to the new nested data structure) and rules.R (for the rules)
- eventually, parsed.R should be replaced in favor of nested.R

@lorenzwalthert: Please merge at your leisure.

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
ok, thanks. Can / should I add a .travis file?

**Comment by krlmlr** [comment]
Thanks for adding .travis.yml.

**Comment by lorenzwalthert** [comment]
cool 👍

**Comment by lorenzwalthert** [comment]
@krlmlr do we delete merged branches?

**Comment by krlmlr** [comment]
Yes, this information is recorded in the history (the second parent of the merge commit).

**Pull request merged**
