### PR TITLE
Communication

### PR DESCRIPTION
**Pull request by lorenzwalthert**
Add informative messages along the way.
```r
style_pkg("tests/testthat/public-api/xyzpackage/")
# styling file R/hello-2.R.                       [DONE]
# styling file R/hello-3.R.                       [DONE]
# styling file R/hello-world.R.                   [DONE]
# styling file tests/testthat/test-package-xyz.R. [DONE]
# No files changed.
```

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
@krlmlr I used an unexported function from utf8 to generate the messages about the number of files changed `ellipsis()`. Maybe we should just copy over the code from there?

**Comment by lorenzwalthert** [comment]
Maybe we can even use `*` next to `"[DONE]" to indicate which ones were changed?
```r
style_pkg("tests/testthat/public-api/xyzpackage/")
# styling file R/hello-2.R.                       [DONE] *
# styling file R/hello-3.R.                       [DONE]
# styling file R/hello-world.R.                   [DONE] *
# styling file tests/testthat/test-package-xyz.R. [DONE]
# *File changed.
```

**Comment by krlmlr** [comment]
Fine with copying `ellipsis()` over here, the star looks good as well.

**Comment by lorenzwalthert** [comment]
Changed the layout slightly.
```r
style_dir("tests/testthat/public-api/xyzpackage//")
#Styling files:
# ./R/hello-2.R.                       [DONE] *
# ./R/hello-3.R.                       [DONE]
# ./R/hello-world.R.                   [DONE]
# ./tests/testthat.R.                  [DONE]
# ./tests/testthat/test-package-xyz.R. [DONE]
# * File changed
# Please review the changes carefully!
```

**Comment by lorenzwalthert** [comment]
Closes #163.

**Pull request merged**
