### PR TITLE
fix parsing inconsistency

### LINKED ISSUE #187: styler executed via console and from within R does not always yield same result
As discussed at https://github.com/krlmlr/dplyr/commit/1c06efc6fa010b98d427b519e2958313895aab5c, styler does not return the same prettified code when run from within R 
```r
styler::style_file("R/bench-compare.r")
```
and from the command line
```bash
R -q -e 'styler::style_file("R/bench-compare.r")'
```

For the majority of other files in this repo (dplyr package), the styling is identical.

### PR DESCRIPTION
**Pull request by lorenzwalthert**
Not to be merged yet. Intended to fix #187. Could be made more functional and flexible so a list of `fix_funs` and one of `valid_funs` could be provided to `fix_p` and they would be applied/used for checking. `fix_pd` is currently really just fixing *one* issue and `is_valid_pd` checks only for this one issue.
Maybe even outsourcing these functions into a separate parsing package, along with issues detected in #100.

### CODE REVIEW

**Comment by lorenzwalthert** [comment]
If this PR goes into the right direction, I can add a test, e.g. for the example introduced in #187.

**Comment by lorenzwalthert** [comment]
Just realized that this PR does not solve the parsing error in  [R/bind.r](https://github.com/lorenzwalthert/dplyr/commits/master) because there, it seems the problem is of a different nature. Need to look into that further.

**Comment by lorenzwalthert** [comment]
Redesigned PR completely according to the recent discussion in #187.

**Comment by krlmlr** [comment]
Great, thanks!

**Pull request merged**
